name: Bubble Form Upload

on:
  workflow_dispatch:
    inputs:
      fileContent:
        description: 'Base64 encoded file content'
        required: true
      fileName:
        description: 'bubbleform' # 'Name of the file'
        required: true

jobs:
  save-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Decode file content
        run: echo ${{ github.event.inputs.fileContent }} | base64 -d > ${{ github.event.inputs.fileName }}

      - name: Commit and push changes
        run: |
          git config user.name 'LarryReader'
          git config user.email 'larryreader@gmail.com'
          git add .
          git commit -m "Add file from Bubble form"
          git push origin main
